# Generated by Django 2.0 on 2019-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ipAddress', models.CharField(max_length=30)),
                ('hostType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'hosts_Hosts',
            },
        ),
    ]
