# Generated by Django 2.0 on 2019-02-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventEngine', '0002_events_alertsource'),
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='inputType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventEngine.InputSource'),
            preserve_default=False,
        ),
    ]
