# Generated by Django 2.1.4 on 2019-02-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0002_hosts_inputtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='inputType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventEngine.InputSource'),
        ),
    ]
