# Generated by Django 2.0 on 2019-02-14 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ActionEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('output_ass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ActionEngine.OutputConfig')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Action_rule_association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RuleEngine.Action')),
            ],
            options={
                'db_table': 'rule_actions',
            },
        ),
        migrations.CreateModel(
            name='HostRuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('desc', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'HostRuleInfo',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_time', models.IntegerField()),
                ('rule_count', models.IntegerField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=256)),
                ('isInterface', models.BooleanField()),
                ('isAlarmType', models.BooleanField()),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='RuleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='event_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RuleEngine.RuleState'),
        ),
        migrations.AddField(
            model_name='hostruleinfo',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RuleEngine.Rule'),
        ),
        migrations.AddField(
            model_name='action_rule_association',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RuleEngine.Rule'),
        ),
        migrations.AddField(
            model_name='action',
            name='rule',
            field=models.ManyToManyField(to='RuleEngine.Rule'),
        ),
    ]
