# Generated by Django 2.0 on 2019-02-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateTimeField()),
                ('userMailId', models.CharField(max_length=32)),
                ('ackNow', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=32)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventEngine.Events')),
            ],
            options={
                'db_table': 'actionengine_mailInfo',
            },
        ),
        migrations.CreateModel(
            name='manageEngineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=1024)),
                ('ticketState', models.CharField(max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, max_length=2048)),
                ('sla', models.CharField(default='', max_length=1024)),
                ('technician', models.CharField(default='', max_length=256)),
                ('resolvedate', models.CharField(default='', max_length=512)),
                ('duebytime', models.CharField(blank=True, default='', max_length=1024)),
                ('responseduebytime', models.CharField(blank=True, default='', max_length=2048)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventEngine.Events')),
            ],
            options={
                'db_table': 'actionengine_manageEngineInfo',
            },
        ),
        migrations.CreateModel(
            name='OutputConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=32)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('techKey', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'actionengine_OutputConfig',
            },
        ),
        migrations.CreateModel(
            name='OutputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'actionengine_OutputType',
            },
        ),
        migrations.CreateModel(
            name='serviceNowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=32)),
                ('ticketState', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventEngine.Events')),
            ],
            options={
                'db_table': 'actionengine_serviceNowInfo',
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(blank=True, max_length=32)),
                ('output_ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActionEngine.OutputType')),
            ],
            options={
                'db_table': 'actionengine_UserConfig',
            },
        ),
        migrations.AddField(
            model_name='outputconfig',
            name='outType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActionEngine.OutputType'),
        ),
    ]
