# Generated by Django 2.1.4 on 2019-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageengineinfo',
            name='priority',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
