# Generated by Django 2.0 on 2019-02-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=256)),
                ('alarmName', models.CharField(blank=True, max_length=256)),
                ('alarmType', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('eventTime', models.DateTimeField(null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('parent', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('assigned', models.CharField(blank=True, max_length=256)),
                ('interface', models.CharField(blank=True, max_length=1024)),
                ('ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hosts.Hosts')),
            ],
            options={
                'db_table': 'eventengine_Events',
            },
        ),
        migrations.CreateModel(
            name='InputSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('serverIp', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'eventengine_InputSource',
            },
        ),
        migrations.CreateModel(
            name='InputSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'eventengine_InputSourceType',
            },
        ),
        migrations.AddField(
            model_name='inputsource',
            name='inputSourceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventEngine.InputSourceType'),
        ),
    ]
