# Generated by Django 2.0 on 2019-02-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='alertSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventEngine.InputSource'),
        ),
    ]
